### ISSUE TITLE
Allow for project names longer than 25 characters

### ISSUE THREAD

**Issue by fenrhil** [openwide-java/artifact-listener#27]
Currently, project names must be between 2 and 25 characters. "25" may be a bit too strict, since one can run over this limit easily.

For instance, I just had to register a project named "yuicompressor-maven-plugin", which is 27 characters long, any of which is useful.

I would suggest raising the upper limit to 50 characters, which should be enough for most use cases while preventing obvious abuses.

**Comment by gsmet** [comment]
Fixed.
