### ISSUE TITLE
Migrate from Google OpenID to Google OAuth2

### ISSUE THREAD

**Issue by gsmet** [openwide-java/artifact-listener#30]
Our old way to sign in with Google isn't supported anymore.

We need to migrate to OAuth2.

A few pointers:
https://arvados.org/blogs/30
https://github.com/pac4j/pac4j/issues/148

**Comment by amertum** [comment]
Is it possible to switch to another provider without loosing all our data, or do we need to wait for this to be implemented ?

**Comment by gsmet** [comment]
I'm working on it. The plan is to allow to migrate transparently to Google OAuth2 API without losing anything. I'll post some news hopefully later this week.

**Comment by gsmet** [comment]
@amertum it should be OK now. You need to log in with Google and create a new account. Your old profile will be copied automatically to your new profile once you validated your account.

**Comment by gsmet** [comment]
Closing. Feel free to ping me if you encounter any issue.

**Comment by amertum** [comment]
@gsmet Awesome ! Everything went fine. Thanks for your work.
