### ISSUE TITLE
The certificate on the website is expired

### ISSUE THREAD

**Issue by wimdeblauwe** [openwide-java/artifact-listener#42]
Chrome gives me a warning when trying to access https://www.artifact-listener.org/ that the HTTPS certificate is not valid (date has expired).

**Comment by gsmet** [comment]
@fenrhil or @lalmeras : open a ticket on XGuard and ask for a renewal. I suppose the order should be addressed to Alain for the time being.

Maybe ask them why they weren't notified of the need for a renewal.

**Comment by lalmeras** [comment]
Already launched action

**Comment by lalmeras** [comment]
SSL renewal done. Thanks for you feedback !
