### ISSUE TITLE
Build support for windows users?

### ISSUE THREAD

**Issue by spyhunter99** [openwide-java/artifact-listener#51]
[2016-12-13 21:57:33,682] WARN  - pertyPlaceholderConfigurer -  - Could not load properties from URL [file:/etc/maven-artifact-notifier/configuration.properties]: \etc\maven-artifact-notifier\configuration.properties (The system cannot find the path specified)

Any idea where this is referenced from? Cause that's not valid on windows. This is when trying to run the database init stuff

**Comment by lalmeras** [comment]
This is a warning and it has no impact on the application as not found configuration files are ignored. So this message can be safely ignored.

About Windows build, we don't have enough time to cross-test our development on this OS. I don't think we rely on any Linux-only functionalities, and I can make an effort to reply to you Windows' related questions, but I can't guarantee we can support it as it depends on the needed amount of work.

If you are interested, I propose to keep this issue opened to talk about it.

**Comment by lalmeras** [comment]
I see in another ticket you successfully run the application. Is it in a Windows environment ? Your answer may be of interest to anyone who want to try artifact-listener on Windows.

**Comment by spyhunter99** [comment]
Working now, it was those asserts statements that broke it. thanks
