### ISSUE TITLE
Suggestion, use another file format instead of microsoft excel for seed data

### ISSUE THREAD

**Issue by spyhunter99** [openwide-java/artifact-listener#54]
xml, csv or json would probably be simpler. Then you wouldn't have binary files in the source repo

**Comment by lalmeras** [comment]
I agree xml or json may be better formats to target a developer audience, but the tool we use to initialize the database is also used by non-technical users in our other projects. As the initialization tool is not very important in this project, I won't spend time on it in the short term. But I welcome any PR for an elegant and simple alternative.
