### ISSUE TITLE
Is https://www.artifact-listener.org/ still updating

### ISSUE THREAD

**Issue by danieljamesscott** [openwide-java/artifact-listener#60]
There haven't been any updates since 8/10/2017 - is this service still alive?

**Comment by gsmet** [comment]
@danieljamesscott 

Good question. The search.maven.org is not very reliable these days and currently the update is "all or nothing". Thus nothing if we get a 500 for at least an artifact - which unfortunately kinda happens nearly every day.

I pushed a PR to fix the issue: https://github.com/openwide-java/artifact-listener/pull/59 . I left the company 1 and a half year ago thus the lake of updates. But @olivierdepriester should apply the PR and deploy it soon hopefully. I think it should fix the update issue.

The idea is to get it up and running soon, especially with version-eye closing.

**Comment by gsmet** [comment]
@danieljamesscott it's updating again.

**Comment by danieljamesscott** [comment]
Excellent, thanks.
