### ISSUE TITLE
Logging via GitHub does not work!

### ISSUE THREAD

**Issue by ilgrosso** [openwide-java/artifact-listener#64]
...and I don't know how to recover: when trying to reset my password, an error message says there is no local password to reset (of course...)

Can you help, please?

**Comment by ilgrosso** [comment]
I have tried to send this issues as e-mail to contact@artifact-listener.org, got an error back.

**Comment by rrramiro** [comment]
I can't singing in with github as well.
I get this error message :
"An unexpected error occurred during the authentication process."

**Comment by gsmet** [comment]
@olivierdepriester anything interesting in the log?

**Comment by julien-gonzalez** [comment]
Could be linked to GitHub recently removing weak crypto standard, including TLS 1.1 for HTTPS communications : https://githubengineering.com/crypto-removal-notice/](https://githubengineering.com/crypto-removal-notice/

**Comment by gsmet** [comment]
Good catch, last time I discussed with @olivierdepriester, he told me it was still using JDK 7.

@olivierdepriester any chance you could update the server to use the latest JDK 8 (not a JDK 9, I'm pretty sure we would have issues with this one). It should just be a matter of unpacking the Oracle archive and change a symlink and then restart the server.

**Comment by marob** [comment]
I've moved to JDK 8. The problem should be solved.

**Comment by ilgrosso** [comment]
I confirm it works now, afte long time, thanks!
