### ISSUE TITLE
Artifact-Listener.org has not synced with central since 16/06/2018

### ISSUE THREAD

**Issue by epkugelmass** [openwide-java/artifact-listener#65]
![image](https://user-images.githubusercontent.com/6265378/44285806-ae7c5280-a21b-11e8-958e-0d0e6f0e9182.png)

You guys are probably aware of this. I'm filing an issue for tracking purposes.

**Comment by tmortagne** [comment]
I guess it has something to do with the API change on http://search.maven.org/.

Just in case: a quickfix might be to use http://search.maven.org/classic/ instead which seems to be the old thing.

**Comment by marob** [comment]
It wasn't an API change, but it's probably linked to "Discontinuing support for TLSv1.1 and below as of June 15th 2018" (see https://maven.apache.org/repository/), even if we're not using SSL for now (we should soon).

It should be fixed now.

**Comment by tmortagne** [comment]
OK, great that you found the fix.

> It should be fixed now.

I confirm I received big mails :)

**Comment by marob** [comment]
Yeah, but I had to try multiple times with minor fixes to make it work. So, I'm waiting next notification to be sure it's OK.
