### ISSUE TITLE
https://www.artifact-listener.org is down

### ISSUE THREAD

**Issue by tmortagne** [openwide-java/artifact-listener#67]
https://www.artifact-listener.org/ seems to be down since very recently (not sure exactly when but I received a mail on Feb 14).

**Comment by marob** [comment]
Thanks for the information, I've notified concerned people and will try to get it back online ASAP.

**Comment by marob** [comment]
It is back online. The batch should run tomorrow and catch up the missing days.
By the way, it was indeed down since 2019/02/15.

**Comment by tmortagne** [comment]
Thanks !
