### ISSUE TITLE
www.artifact-listener.org down

### ISSUE THREAD

**Issue by MrEasy** [openwide-java/artifact-listener#78]
Hi,

Not a code issue, but community seems to be more active here than on Twitter.
www.artifact-listener.org is down for quite some time - is this known and any estmation if/when it will be back.

Thank you!

**Comment by marob** [comment]
Hi, thanks for the notification. I'll look into it.

**Comment by marob** [comment]
This is back online. Sorry for the inconvenience.

**Comment by MrEasy** [comment]
Great - thanks!
